FROM node:14.15.5-alpine3.13 as builder

WORKDIR /workspace

COPY ./app/ .

RUN npm install

RUN npm run build

FROM nginx:stable-alpine

COPY ./infra/app/nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /workspace/dist /usr/share/nginx/html/

EXPOSE 80
